In [6]:
import numpy as np
import pandas as pd
import os, sys
import pprint

In [7]:
dataset_name = 'splice'
inp_fname = 'splice.data'

In [8]:
input_dir = './raw'
output_dir = './processed'

outp_fname = os.path.join(output_dir, f'{dataset_name}.csv')
outp_train_fname = os.path.join(output_dir, f'{dataset_name}_train.csv')
outp_test_fname = os.path.join(output_dir, f'{dataset_name}_test.csv')
outp_test_key_fname = os.path.join(output_dir, f'{dataset_name}_test_key.csv')

# Read Data

In [9]:
cols = [
    "Class",
    "Instance"
] + [f"G_{i}" for i in range(60)]

print(cols)

['Class', 'Instance', 'G_0', 'G_1', 'G_2', 'G_3', 'G_4', 'G_5', 'G_6', 'G_7', 'G_8', 'G_9', 'G_10', 'G_11', 'G_12', 'G_13', 'G_14', 'G_15', 'G_16', 'G_17', 'G_18', 'G_19', 'G_20', 'G_21', 'G_22', 'G_23', 'G_24', 'G_25', 'G_26', 'G_27', 'G_28', 'G_29', 'G_30', 'G_31', 'G_32', 'G_33', 'G_34', 'G_35', 'G_36', 'G_37', 'G_38', 'G_39', 'G_40', 'G_41', 'G_42', 'G_43', 'G_44', 'G_45', 'G_46', 'G_47', 'G_48', 'G_49', 'G_50', 'G_51', 'G_52', 'G_53', 'G_54', 'G_55', 'G_56', 'G_57', 'G_58', 'G_59']

In [10]:
# Import the file, you may need to adjust path, this assumes it's in cwd
path = os.getcwd()
f=open(os.path.join(input_dir, inp_fname), "r")

# puts the data into a list array Nx3, and removes newlines
lines = [line.rstrip('\n') for line in f]


def split(word): return [char for char in word]

all_items = []
for line in lines:
    # strips whitespace
    items = line.replace(" ","")
    items = items.split(",")
    seq_split = split(items[-1])
    items = items[:-1] + seq_split
    all_items.append(items)

data_array = np.asarray(all_items)

data = pd.DataFrame(data_array, columns=cols)
data.head()

,Class,Instance,G_0,G_1,G_2,G_3,G_4,G_5,G_6,G_7,...,G_50,G_51,G_52,G_53,G_54,G_55,G_56,G_57,G_58,G_59
0,EI,ATRINS-DONOR-521,C,C,A,G,C,T,G,C,...,A,G,C,C,A,G,T,C,T,G
1,EI,ATRINS-DONOR-905,A,G,A,C,C,C,G,C,...,G,T,G,C,C,C,C,C,G,C
2,EI,BABAPOE-DONOR-30,G,A,G,G,T,G,A,A,...,C,A,C,G,G,G,G,A,T,G
3,EI,BABAPOE-DONOR-867,G,G,G,C,T,G,C,G,...,G,G,T,T,T,T,C,C,C,C
4,EI,BABAPOE-DONOR-2817,G,C,T,C,A,G,C,C,...,C,C,T,T,G,A,C,C,C,T

In [12]:
id_col = "Instance"
target_col = "Class"

# Insert Id Column

In [13]:
# insert Id column 
if id_col not in data.columns:
    N = data.shape[0]
    data.insert(0, id_col, np.arange(N))
    print(data.head())

# Shuffle Data

In [14]:
# shuffle data
data = data.sample(frac=1, random_state=42)
data.head()

,Class,Instance,G_0,G_1,G_2,G_3,G_4,G_5,G_6,G_7,...,G_50,G_51,G_52,G_53,G_54,G_55,G_56,G_57,G_58,G_59
1029,IE,HUMDES-ACCEPTOR-3015,T,C,C,T,T,G,A,C,...,G,A,T,G,C,G,G,G,A,A
1001,IE,HUMCSFGMA-ACCEPTOR-891,T,T,G,A,T,A,A,C,...,C,T,C,A,G,A,A,A,T,G
785,IE,HUMA1ATP-ACCEPTOR-10909,C,A,T,G,C,C,T,T,...,C,C,A,A,A,C,T,G,T,C
411,EI,HUMIL1B-DONOR-416,G,A,T,T,C,T,C,T,...,A,C,A,A,C,T,A,G,G,T
1105,IE,HUMGHCSA-ACCEPTOR-27717,T,C,C,C,T,C,C,A,...,C,T,G,G,C,T,T,T,T,G

# Save Main Data File

In [15]:
data.to_csv(outp_fname, index=False)

# Train Test Split

In [16]:
from sklearn.model_selection import train_test_split
test_size = 0.1

data_train, data_test = train_test_split(data, test_size=test_size, random_state=42)
print(data_train.shape, data_test.shape)

data_train.to_csv(outp_train_fname, index=False)
data_test.drop(columns=[target_col]).to_csv(outp_test_fname, index=False)
data_test[[id_col, target_col]].to_csv(outp_test_key_fname, index=False)

(2871, 62) (319, 62)